// USER FORM CONSTANTS
export const ACTIVE_STEP_INCREMENT = "ACTIVE_STEP_INCREMENT";
export const ACTIVE_STEP_DECRAMENT = "ACTIVE_STEP_DECRAMENT";
export const ACTIVE_STEP_RESET = "ACTIVE_STEP_RESET";
export const ADD_DATA_TO_ALL_INFORMATION = "ADD_DATA_TO_ALL_INFORMATION";

// STEP 1. PERSONAL DETAILS
export const SET_PERSONAL_FIELD = "SET_PERSONAL_FIELD";
export const SET_PERSONAL_ERRORS = "SET_PERSONAL_ERRORS";

// STEP 2. CONTACT DETAILS
export const SET_CONTACT_FIELD = "SET_CONTACT_FIELD";
export const SET_CONTACT_ERRORS = "SET_CONTACT_ERRORS";

// STEP 3. PAYMENT DETAILS
export const SET_PAYMENT_FIELD = "SET_PAYMENT_FIELD";
export const SET_PAYMENT_ERRORS = "SET_PAYMENT_ERRORS";
