export const ACTIVE_STEP_INCREMENT = "ACTIVE_STEP_INCREMENT";
export const ACTIVE_STEP_DECRAMENT = "ACTIVE_STEP_DECRAMENT";
export const ACTIVE_STEP_RESET = "ACTIVE_STEP_RESET";
export const ADD_DATA_TO_ALL_INFORMATION = "ADD_DATA_TO_ALL_INFORMATION";
