// USER FORM CONSTANTS
export const ACTIVE_STEP_INCREMENT = "ACTIVE_STEP_INCREMENT";
export const ACTIVE_STEP_DECRAMENT = "ACTIVE_STEP_DECRAMENT";
export const RESET_ALL_FORM = "RESET_ALL_FORM";
export const ADD_DATA_TO_ALL_INFORMATION = "ADD_DATA_TO_ALL_INFORMATION";
export const SET_THEME_TYPE = "SET_THEME_TYPE";
export const SET_LANGUAGE_APP = "SET_LANGUAGE_APP";

// STEP 1. PERSONAL DETAILS
export const SET_PERSONAL_FIELD = "SET_PERSONAL_FIELD";
export const SET_PERSONAL_ERRORS = "SET_PERSONAL_ERRORS";
export const RESET_PERSONAL_STEP = "RESET_PERSONAL_STEP";

// STEP 2. CONTACT DETAILS
export const SET_CONTACT_FIELD = "SET_CONTACT_FIELD";
export const SET_CONTACT_ERRORS = "SET_CONTACT_ERRORS";
export const RESET_CONTACT_STEP = "RESET_CONTACT_STEP";

// STEP 3. PAYMENT DETAILS
export const SET_PAYMENT_FIELD = "SET_PAYMENT_FIELD";
export const SET_PAYMENT_ERRORS = "SET_PAYMENT_ERRORS";
export const RESET_PAYMENT_STEP = "RESET_PAYMENT_STEP";
